### Arange in Numpy

In [1]:
import numpy as np

In [13]:
a=np.arange(0,20) #(start,end,step)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [14]:
b=np.arange(1,10,3)
print(b)

[1 4 7]


In [15]:
#Printing all even numbers using numpy Array
c=np.arange(2,20,2)

#### Reshape in Numpy

In [16]:
def Resp(row,col,arr):
    if (arr.size==row*col):
        arr=arr.reshape((row,col))
        print(arr)
    else:
        print("Reshape Not Possible")
Resp(4,5,a)
        
    

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


### Flatening the array

In [17]:
a.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

### Ravel in Numpy

In [18]:
a.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

### Ravel :Return only refrence, faster than flatten(),Library level Function,value of original array will also change,doesnot occupy Memory

### flatten: Returns copy of original array,original value of array is not affected, method of an ndarray object,occupies memory,slower than ravel