In [1]:
import numpy as np

### Mathematical Operations in Numpy

In [7]:
a=np.arange(10,30).reshape(4,5)
b=np.arange(1,40,2).reshape(4,5)


In [12]:
print(a)
print(" ")
print(b)

[[10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]
 
[[ 1  3  5  7  9]
 [11 13 15 17 19]
 [21 23 25 27 29]
 [31 33 35 37 39]]


In [13]:
a-b #Similiar index wala element will get affected

array([[  9,   8,   7,   6,   5],
       [  4,   3,   2,   1,   0],
       [ -1,  -2,  -3,  -4,  -5],
       [ -6,  -7,  -8,  -9, -10]])

In [14]:
a+b

array([[11, 14, 17, 20, 23],
       [26, 29, 32, 35, 38],
       [41, 44, 47, 50, 53],
       [56, 59, 62, 65, 68]])

In [15]:
a*b

array([[  10,   33,   60,   91,  126],
       [ 165,  208,  255,  306,  361],
       [ 420,  483,  550,  621,  696],
       [ 775,  858,  945, 1036, 1131]])

In [16]:
a/b

array([[10.        ,  3.66666667,  2.4       ,  1.85714286,  1.55555556],
       [ 1.36363636,  1.23076923,  1.13333333,  1.05882353,  1.        ],
       [ 0.95238095,  0.91304348,  0.88      ,  0.85185185,  0.82758621],
       [ 0.80645161,  0.78787879,  0.77142857,  0.75675676,  0.74358974]])

###  Product in Matrix

In [17]:
np.multiply(a,b)

array([[  10,   33,   60,   91,  126],
       [ 165,  208,  255,  306,  361],
       [ 420,  483,  550,  621,  696],
       [ 775,  858,  945, 1036, 1131]])

### Proper Matrix Multiplication 

In [19]:
 #Remember col of first matrix and row of second Matrix must be Identical
a@b

### Finding Maximum Minimum of array

In [20]:
a.max()

29

In [21]:
a.min()

10

In [22]:
#index of a.max() will be given by argmax()
a.argmax()

19

### Finding Sum of All array elements

In [23]:
#axis=1 means rows
np.sum(a,axis=1)

array([ 60,  85, 110, 135])

In [24]:
np.sum(b)

400

In [25]:
np.mean(a) #Finding Mean of Array

19.5

In [26]:
np.sqrt(a)

array([[3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739],
       [3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894],
       [4.47213595, 4.58257569, 4.69041576, 4.79583152, 4.89897949],
       [5.        , 5.09901951, 5.19615242, 5.29150262, 5.38516481]])

In [27]:
np.log(b)

array([[0.        , 1.09861229, 1.60943791, 1.94591015, 2.19722458],
       [2.39789527, 2.56494936, 2.7080502 , 2.83321334, 2.94443898],
       [3.04452244, 3.13549422, 3.21887582, 3.29583687, 3.36729583],
       [3.4339872 , 3.49650756, 3.55534806, 3.61091791, 3.66356165]])