In [1]:
import numpy as np

### Row Acessing

In [3]:
a=np.arange(0,20,2)
a=a.reshape((5,2))
print(a)


[[ 0  2]
 [ 4  6]
 [ 8 10]
 [12 14]
 [16 18]]


In [4]:
a[1][1]

6

In [5]:
a[0][-1]

2

In [8]:
a[:2] #[Row:Col]

array([[0, 2],
       [4, 6]])

In [9]:
a[: , :3] #[row,col][: , :]

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10],
       [12, 14],
       [16, 18]])

In [14]:
a[:1,:]

array([[0, 2]])