In [ ]:
import numpy as np

In [3]:
np.random.random(1) #Denotes Number of Elements

array([0.81925514])

In [4]:
np.random.random(2)

array([0.91722632, 0.14799033])

In [5]:
np.random.random((2,2))

array([[0.06205461, 0.05443667],
       [0.35170546, 0.37981611]])

In [6]:
np.random.random((2,3,4))

array([[[0.93107225, 0.00161234, 0.4416883 , 0.06655483],
        [0.46413727, 0.84324023, 0.02982207, 0.23770123],
        [0.66778909, 0.93155167, 0.96575125, 0.06685793]],

       [[0.70536343, 0.01784284, 0.14288813, 0.5730392 ],
        [0.81297922, 0.37337731, 0.6590476 , 0.00811547],
        [0.67217029, 0.19622327, 0.09540068, 0.65528616]]])

In [9]:
np.random.randint(1,10) #generate random between 1 to 10

3

In [12]:
np.random.randint(1,10,(2,2)) #Generate 2X2 matrix using random 1 to 1o

array([[8, 5],
       [1, 2]])

In [13]:
np.random.rand(1,30) #float datatype

array([[0.68182371, 0.21310733, 0.07467161, 0.26323177, 0.75020297,
        0.0685364 , 0.48466759, 0.59371447, 0.2018965 , 0.43936687,
        0.57921495, 0.57067098, 0.13861375, 0.81898583, 0.05746876,
        0.55672201, 0.98019591, 0.59105445, 0.31118717, 0.27119262,
        0.66335444, 0.24085674, 0.12220121, 0.84280635, 0.6111054 ,
        0.73152219, 0.99072852, 0.56646887, 0.11662586, 0.4940229 ]])

In [20]:
np.random.randn(2,2) #n denotes negative value are  allowed here

array([[-0.3294062 , -1.01835335],
       [-0.09954761,  0.9468549 ]])

In [18]:
a=np.arange(1,5)
np.random.choice(a) #It will select random element from this numpy

1