In [1]:
import numpy as np

#### np.empty((rows,cols),dtype) will returen array of rows*cols having random values

In [2]:
np.empty((3,5),dtype=float) #prvoiding rows and columns as tuple

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        1.29061074e-306, 7.56587585e-307],
       [1.37961302e-306, 1.05699242e-307, 8.01097889e-307,
        1.78020169e-306, 7.56601165e-307],
       [1.02359984e-306, 1.33510679e-306, 2.22522597e-306,
        8.01097889e-307, 0.00000000e+000]])

In [3]:
np.ones((1,5),dtype=int)

array([[1, 1, 1, 1, 1]])

In [6]:
np.zeros((2,3),dtype=int)

array([[0, 0, 0],
       [0, 0, 0]])

In [7]:
np.zeros(4)

array([0., 0., 0., 0.])

In [8]:
np.ones((3,5),dtype=bool) #All value will be True

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [9]:
np.zeros((2),dtype=bool) #All Values will be false

array([False, False])